# Generated by Django 5.1.6 on 2025-03-03 19:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiences', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('participants', models.PositiveIntegerField(default=1)),
                ('total_price', models.FloatField()),
                ('booking_date', models.DateField()),
                ('experience_date', models.DateField()),
                ('cancellable', models.BooleanField()),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('CANCELLED', 'Cancelada'), ('CONFIRMED', 'Confirmada')], default='PENDING', max_length=50)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='experiences.experience')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='users.usuario')),
            ],
        ),
    ]
