# Generated by Django 5.1.6 on 2025-03-06 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('users', '0003_alter_usuario_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.FloatField(default=10, help_text='Precio por persona de la reserva. Debería ser el mismo que el de la experiencia, de los rangos de precio que haya.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('CANCELLED', 'Cancelada'), ('CONFIRMED', 'Confirmada')], default='PENDING', help_text="Estado de la reserva. Comienza en 'PENDING' y se actualiza según se asigne la experiencia.", max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.FloatField(help_text='Precio total de la reserva. Precio por persona multiplicado por el número de participantes.'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='users.usuario'),
        ),
    ]
