# Generated by Django 5.1.6 on 2025-03-24 17:48

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_price_alter_booking_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='participants',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.FloatField(help_text='Precio por persona de la reserva. Debería ser el mismo que el de la experiencia, de los rangos de precio que haya.', validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.FloatField(help_text='Precio total de la reserva. Precio por persona multiplicado por el número de participantes.', validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
