# Generated by Django 5.1.7 on 2025-03-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_participants_alter_booking_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hint_sent',
            field=models.BooleanField(default=False, help_text='Indica si ya se envió el correo con la pista para esta reserva.'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('CANCELLED', 'Cancelada'), ('CONFIRMED', 'Confirmada')], default='PENDING', help_text="Estado de la reserva. Comienza en 'PENDING' y puede ser modificado por el administrador una vez se asigne la experiencia.", max_length=50),
        ),
    ]
