# Generated by Django 5.1.7 on 2025-04-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_participants_alter_booking_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('CANCELLED', 'Cancelada'), ('CONFIRMED', 'Confirmada')], default='PENDING', help_text="Estado de la reserva. Comienza en 'PENDING' y puede ser modificado por el administrador una vez se asigne la experiencia.", max_length=50),
        ),
    ]
