# Generated by Django 5.1.6 on 2025-02-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reserva',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('momento', models.CharField(choices=[('Mañana', 'Mañana'), ('Medio dia', 'Medio Dia'), ('Tarde', 'Tarde'), ('Noche', 'Noche')])),
                ('categoria', models.CharField(choices=[('Musica', 'Musica'), ('Cultura y arte', 'Cultura Y Arte'), ('Deporte y motor', 'Deporte Y Motor'), ('Gastronomia', 'Gastronomia'), ('Ocio nocturno', 'Ocio Nocturno'), ('aventura', 'Aventura')])),
                ('asistentes', models.IntegerField()),
                ('pista', models.TextField(blank=True, null=True)),
                ('ubicacion', models.TextField(blank=True, null=True)),
                ('Url_organizador', models.URLField(blank=True, null=True)),
                ('coste_por_persona', models.FloatField()),
            ],
        ),
    ]
