# Generated by Django 5.1.6 on 2025-03-06 20:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiences', '0003_alter_experience_description_alter_experience_hint_and_more'),
        ('users', '0004_usuario_adventure_usuario_culture_usuario_gastronomy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('puntuacion', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('comentario', models.TextField(max_length=250)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='experiences.experience')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.usuario')),
            ],
        ),
    ]
