# Generated by Django 5.1.6 on 2025-02-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=100)),
                ('nick', models.CharField(max_length=100)),
                ('pfp', models.ImageField(upload_to='')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
