# Generated by Django 5.1.6 on 2025-03-05 15:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['-surname']},
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['-surname'], name='users_usuar_surname_d074fb_idx'),
        ),
    ]
