# Generated by Django 5.1.6 on 2025-03-09 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_usuario_adventure_usuario_culture_usuario_gastronomy_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(model_name="usuario", name="adventure",),
        migrations.RemoveField(model_name="usuario", name="culture",),
        migrations.RemoveField(model_name="usuario", name="gastronomy",),
        migrations.RemoveField(model_name="usuario", name="music",),
        migrations.RemoveField(model_name="usuario", name="nightlife",),
        migrations.RemoveField(model_name="usuario", name="sports",),
        migrations.AlterField(
            model_name="usuario",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usuario",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Preferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("music", models.JSONField(default=list)),
                ("culture", models.JSONField(default=list)),
                ("sports", models.JSONField(default=list)),
                ("gastronomy", models.JSONField(default=list)),
                ("nightlife", models.JSONField(default=list)),
                ("adventure", models.JSONField(default=list)),
                (
                    "dietary_restrictions",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("budget_range", models.JSONField(blank=True, default=list, null=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to="users.usuario",
                    ),
                ),
            ],
        ),
    ]
