# Generated by Django 5.1.6 on 2025-03-10 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_usuario_adventure_remove_usuario_culture_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="preferences", name="budget_range",),
        migrations.RemoveField(model_name="preferences", name="dietary_restrictions",),
    ]
