# Generated by Django 5.1.6 on 2025-03-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_preferences_budget_range_and_more'),
    ]

    operations = [
    ]
