# Generated by Django 5.1.6 on 2025-03-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_preferences_budget_range_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="birthdate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="phone",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
