# Generated by Django 5.1.7 on 2025-03-26 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_usuario_birthdate'),
        ('users', '0007_usuario_birthdate_alter_usuario_phone'),
    ]

    operations = [
    ]
