# Generated by Django 5.1.7 on 2025-03-26 16:35

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_20250326_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email_verification_sent_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='email_verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='birthdate',
            field=models.DateField(blank=True, default='2003-11-07', null=True),
        ),
    ]
