# Generated by Django 5.1.7 on 2025-04-05 08:01

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_usuario_email_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.profile_pic_path),
        ),
    ]
