# Generated by Django 5.1.6 on 2025-03-03 19:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('location', models.CharField(max_length=50)),
                ('duration', models.PositiveIntegerField()),
                ('hint', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('category', models.CharField(choices=[('ADVENTURE', 'Aventura'), ('CULTURE', 'Cultura'), ('SPORTS', 'Deporte'), ('GASTRONOMY', 'Gastronomía'), ('NIGHTLIFE', 'Ocio nocturno'), ('MUSIC', 'Música')], max_length=50)),
            ],
        ),
    ]
