# Generated by Django 5.1.6 on 2025-03-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_alter_experience_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='hint',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='experience',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Precio por persona de la experiencia. Deberían haber rangos de precios prefijados.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
