# Generated by Django 5.1.6 on 2025-03-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0003_alter_experience_description_alter_experience_hint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='category',
        ),
        migrations.AddField(
            model_name='experience',
            name='categories',
            field=models.JSONField(default=list, help_text='Lista de categorías (máximo 3)'),
        ),
    ]
