# Generated by Django 5.1.6 on 2025-03-24 17:48

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0004_remove_experience_category_experience_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='notas_adicionales',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Precio por persona de la experiencia. Deberían haber rangos de precios prefijados.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
